pipeline {

    agent any

    tools {
        node '20.3.0'
    }

    stages {

        stage ('Compilar'){
            steps {
                echo 'Compilando ....'
                sh 'npm install'
            }
        }
    }
}